name: "JFrog GitHub Demo"
on:
  push:
    branches: [demo-jfrogchina]

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: write
  pull-requests: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_CHINA_URL }}
        with:
          oidc-provider-name: slash-github
          oidc-audience: slash-github-audience

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          jf c show

      - name: Run JFrog CLI Frogbot Scan
        uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ vars.JF_CHINA_URL }}
          JF_GIT_TOKEN: ${{ secrets.SLASH_GITHUB_TOKEN }}
        with:
          oidc-provider-name: slash-github
      
      - name: Build and Publish NPM Package
        working-directory: ./app-npm  # 设置工作目录
        run: |
          echo "当前目录: $(pwd)"
          jf npmc --server-id-resolve=setup-jfrog-cli-server --server-id-deploy=setup-jfrog-cli-server --repo-resolve=slash-npm-virtual --repo-deploy=slash-npm-virtual
          jf npm install --build-name=slash-jpd-github-npm --build-number=${{github.run_number}}
          jf npm publish --build-name=slash-jpd-github-npm --build-number=${{github.run_number}}
          jf rt bce slash-jpd-github-npm ${{github.run_number}}
          jf rt bp slash-jpd-github-npm ${{github.run_number}}
          
      - name: Build and Publish NPM Package
        working-directory: ./app-npm  # 设置工作目录
        run: |
          echo "Xray Scan Build Artifacts"
          jf bs slash-jpd-github-npm ${{github.run_number}}
