name: "JFrog GitHub Demo"
on:
  push:
    branches: [demo-jfrogchina]

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: write
  pull-requests: write
  security-events: write
  attestations: write
  artifact-metadata: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_CHINA_URL }}
        with:
          oidc-provider-name: slash-github
          oidc-audience: slash-github-audience

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          jf c show

      # - name: Run JFrog CLI Frogbot Scan
      #   uses: jfrog/frogbot@v2
      #   env:
      #     JF_GIT_TOKEN: ${{ secrets.SLASH_GITHUB_TOKEN }}
      #     # JF_URL: ${{ vars.JF_CHINA_URL }}
      #     # JF_ACCESS_TOKEN: ${{ secrets.JF_CHINA_ACCESS_TOKEN }}
      #     JF_URL: ${{ vars.JF_URL }}
      #     JF_ACCESS_TOKEN: ${{ secrets.JF_SOLENG_ACCESS_TOKEN }}


        # with:
        #   oidc-provider-name: slash-github
        #   oidc-audience: slash-github-audience
      
      - name: Run JFrog Curation Audit
        working-directory: ./app-npm  # 设置工作目录
        run: jf curation-audit

      - name: Build and Publish NPM Package
        working-directory: ./app-npm  # 设置工作目录
        run: |
          echo "当前目录: $(pwd)"

          VERSION=$(node -p "require('./package.json').version")
          BASE_VERSION=${VERSION%.*}  # 获取主版本号 1.0
          
          # 使用 GitHub Actions 的 run_number 作为构建号
          BUILD_NUMBER=${{ github.run_number }}

          npm version ${BASE_VERSION}.${BUILD_NUMBER} --no-git-tag-version

          jf npmc --server-id-resolve=setup-jfrog-cli-server --server-id-deploy=setup-jfrog-cli-server --repo-resolve=slash-npm-virtual --repo-deploy=slash-npm-virtual
          jf npm install --build-name=slash-jpd-github-npm --build-number=${{github.run_number}}
          jf npm publish --build-name=slash-jpd-github-npm --build-number=${{github.run_number}}
          jf rt bce slash-jpd-github-npm ${{github.run_number}}
          jf rt bp slash-jpd-github-npm ${{github.run_number}}
          
      - name: Xray Scan Build Artifacts
        working-directory: ./app-npm  # 设置工作目录
        run: |
          echo "Xray Scan Build Artifacts"
          jf bs slash-jpd-github-npm ${{github.run_number}}

      # - name: Attest Send to JFrog Evidence
      #   uses: actions/attest-build-provenance@v3
      #   with:
      #     # The 'oci://' prefix is required by JFrog to correctly parse the artifact type
      #     # subject-name: npm://demo.jfrogchina.com/artifactory/slash-npm-dev-local/app-npm/app-npm:1.0.0
          
      #     # This links the attestation directly to the image digest from the build step
      #     subject-digest: sha256:67695ebf9f9e2c612336a1e77af73d7ffbe6e9af72d1629411e19120af352a80
