name: "Setup JFrog CLI OIDC Example"
on:
  push:
    branches: [demo-jfrogchina]

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_CHINA_URL }}
        with:
          oidc-provider-name: slash-github
          oidc-audience: slash-github-audience

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          jf c show
      
      - name: Build and Publish NPM Package
        working-directory: ./app-npm  # 设置工作目录
        run: |
          echo "当前目录: $(pwd)"
          # jf npmc 
          # jf npm install --build-name=slash-jpd-github-npm --build-number=1
          # jf npm publish --build-name=slash-jpd-github-npm --build-number=1
          # jf rt bce slash-jpd-github-npm 1
          # jf rt bp slash-jpd-github-npm 1
          
